# This workflow integrates REST API Static Security Testing with GitHub's code scanning feature
# REST API Static Security Testing by 42Crunch checks your OpenAPI files for their quality and security

name: REST API Static Security Testing

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on: push

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Please create free account at https://platform.42crunch.com/register
    # Follow these steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
    - name: 42Crunch REST API Static Security Testing
      uses: 42Crunch/api-security-audit-action@v1
      with:
        api-token: ${{ secrets.API_TOKEN }}
        upload-to-code-scanning: true
